#
#  MinoDX's Expansion PLugin (Powered by MinoMC_YTB)
#  Version: 0.1-SNAPSHOT-4
#

#  Placeholders for chat format, support PlaceholderAPI:
#  {player} - Get player name
#  {message} - Get chat message
chat-format: '{player}: {message}'

join-message: '&a[+] &r{player} joined the server!'
leave-message: '&c[-] &r{player} left the server.'

scoreboard:
  title: "&a&lYour Server"
  lines:
    - "&7Welcome, &f%player_name%"
    - "&eOnline: &f%server_online%"
    - "&6Ping: &f%player_ping%"
    - "&aCoins: &f%vault_eco_balance%"
    - ""
    - "&bYour Rank: &f%luckperms_prefix%"
    - "&cyourserver.com"

tab-format:
  header: "&aWelcome!"
  footer: "&bHave a great time!"