name: MD Expansion
version: '0.1-SNAPSHOT'
main: com.minodx.MDExpansion.MDExpansion
api-version: '1.20'
authors: [ MinoMC_YTB ]
description: A simple plugin contains some configurable formats

softdepend: ["PlaceholderAPI"]