name: MDE
version: '0.1-SNAPSHOT'
main: com.minodx.MDExpansion.MDExpansion
api-version: '1.20'
authors: [ MinoMC_YTB ]
description: A simple plugin contains some configurable formats

depend: [LuckPerms, PlaceholderAPI]

commands:
  mde:
    description: Plugin main command.
    permission: mde.admin.reload
    usage: "Usage: /mde reload"
    aliases: [mder, mdereload]